export enum ErrorCode {
  // Generic
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  BAD_REQUEST = 'BAD_REQUEST',

  // Consent
  DATA_REQUEST_NOT_FOUND = 'DATA_REQUEST_NOT_FOUND',
  CONSENT_NOT_FOUND = 'CONSENT_NOT_FOUND',
  CONSENT_ALREADY_DECIDED = 'CONSENT_ALREADY_DECIDED',
  REQUEST_EXPIRED = 'REQUEST_EXPIRED',

  // Claims
  CLAIM_NOT_FOUND = 'CLAIM_NOT_FOUND',
  CLAIM_KEY_ALREADY_EXISTS = 'CLAIM_KEY_ALREADY_EXISTS',
  CLAIMS_NOT_FOUND = 'CLAIMS_NOT_FOUND',
  CLAIMS_NOT_AUTHORIZED = 'CLAIMS_NOT_AUTHORIZED',

  // Wallet
  USER_SUBJECT_NOT_FOUND = 'USER_SUBJECT_NOT_FOUND',
  PRESENTATION_SESSION_NOT_FOUND = 'PRESENTATION_SESSION_NOT_FOUND',
  SESSION_ALREADY_COMPLETED = 'SESSION_ALREADY_COMPLETED',

  // Partner
  PARTNER_NOT_FOUND = 'PARTNER_NOT_FOUND',
  ISSUER_NOT_FOUND = 'ISSUER_NOT_FOUND',
  CONSUMER_NOT_FOUND = 'CONSUMER_NOT_FOUND',
  CREDENTIAL_NOT_FOUND = 'CREDENTIAL_NOT_FOUND',

  // Config / Feature
  CONFIG_INVALID = 'CONFIG_INVALID',
  FEATURE_DISABLED = 'FEATURE_DISABLED',
}
